"""
Build the Publications section of index.html from publications.toml.

publications.toml is the single source of truth. This script loads it (stdlib
tomllib — no third-party deps) and renders each publication into an <article>,
injected between markers in index.html so the build is idempotent:

    <!-- PUBLICATIONS:START (generated by tools/build.py — do not edit) -->
    <!-- PUBLICATIONS:END -->

Each publication may define:
    title, authors, year, doi, preprint   -> title link + preprint link
    code                                   -> "code" link
    [publication.materials] name = url     -> one link per named material
    tags                                   -> dithered thumbnail (via gen_dither)

Author display (initials, bold "me", co-author links) is configured in authors.py.

Usage:
    python tools/build.py            # rebuild index.html in place
    python tools/build.py --check    # exit 1 if index.html would change (CI)
"""

import html
import re
import sys
import unicodedata
from pathlib import Path

import tomllib

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
TOML = ROOT / "assets" / "publications.toml"
INDEX = ROOT / "index.html"

sys.path.insert(0, str(HERE))

ME = "Tarek Kunze"
ME_ALIASES = [
    "Tarek Kunze",
    "T. Kunze",
]
AUTHOR_SITES = {
    "Maxime Poli": "https://mpoli.fr/",
    "Marvin Lavechin": "https://marvinlvn.github.io/",
    "Dennis G. Wilson": "https://d9w.github.io/",
}

START = "<!-- PUBLICATIONS:START (generated by tools/build.py — do not edit) -->"
END = "<!-- PUBLICATIONS:END -->"

# order of the small link row under each paper (known labels first, then extras)
LINK_ORDER = ["paper", "code", "preprint", "poster", "slides", "video"]


# --------------------------------------------------------------------- helpers
def norm(s):
    s = unicodedata.normalize("NFKD", s or "")
    s = "".join(c for c in s if not unicodedata.combining(c))
    return re.sub(r"\s+", " ", s).strip().lower()


def slugify(title):
    """Title -> lowercase slug with no spaces or special characters."""
    s = unicodedata.normalize("NFKD", title or "")
    s = "".join(c for c in s if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


ME_KEYS = {norm(a) for a in ME_ALIASES} | {norm(ME)}


def initials(name):
    """'Marvin Lavechin' -> 'M. Lavechin'; 'Kaveri K. Sheth' -> 'K. K. Sheth'."""
    toks = name.split()
    if len(toks) == 1:
        return toks[0]
    *firsts, last = toks
    ini = " ".join((t if t.endswith(".") else t[0] + ".") for t in firsts)
    return f"{ini} {last}"


def author_site(name):
    nk = norm(name)
    for site_name, url in AUTHOR_SITES.items():
        if norm(site_name) == nk:
            return url
    return None


def format_authors(names):
    chunks = []
    for name in names:
        disp = html.escape(initials(name))
        if norm(name) in ME_KEYS:
            chunks.append(f"<b>{disp}</b>")
        else:
            url = author_site(name)
            chunks.append(
                f'<a href="{html.escape(url)}" target="_blank" '
                f'rel="noopener noreferrer">{disp}</a>'
                if url
                else disp
            )
    if len(chunks) <= 1:
        return "".join(chunks)
    if len(chunks) == 2:
        return f"{chunks[0]} and {chunks[1]}"
    return ", ".join(chunks[:-1]) + " and " + chunks[-1]


def doi_url(pub):
    doi = pub.get("doi", "")
    if not doi:
        return None
    return doi if doi.startswith("http") else f"https://doi.org/{doi}"


def collect_links(pub, title_url=None):
    """Return an ordered list of (label, url) for the link row."""
    links = {}
    if pub.get("code"):
        links["code"] = pub["code"]
    if pub.get("preprint"):  # and pub["preprint"] != title_url:
        links["preprint"] = pub["preprint"]
    for label, url in (pub.get("materials") or {}).items():
        links[label] = url
    ordered = [(l, links[l]) for l in LINK_ORDER if l in links]
    ordered += [(l, u) for l, u in links.items() if l not in LINK_ORDER]
    return ordered


# ------------------------------------------------------------------- rendering
def render(pub):
    title = re.sub(r"\s+", " ", pub["title"]).strip()
    slug = slugify(title)
    title_url = doi_url(pub) or pub.get("preprint") or "#"
    authors_html = format_authors(pub.get("authors", []))

    links = collect_links(pub, title_url)
    link_lines = "\n".join(
        f'                    <a href="{html.escape(url)}" target="_blank" '
        f'rel="noopener noreferrer">{html.escape(label)}</a>'
        for label, url in links
    )
    links_block = (
        f"""
                <div class="links">
{link_lines}
                </div>"""
        if links
        else ""
    )

    venue_s = ""
    if "venue_shortcode" in pub:
        venue_s = pub["venue_shortcode"]
    elif pub["type"] == "misc":
        venue_s = f"arXiv"
    elif "" in pub:
        venue_s = pub["booktitle"]

    return f"""        <article class="paper">
            <div class="paper-thumb"><img src="dither/{slug}.png" alt="" width="44" height="44" loading="lazy" /></div>
            <div class="paper-body">
                <a class="title" href="{html.escape(title_url)}" target="_blank" rel="noopener noreferrer">
                    {html.escape(title)}
                </a>
                <span class="meta authors">{authors_html}</span>
                <span class="venue">{venue_s} {pub["year"]}</span>
                {links_block}
            </div>
        </article>"""


def load_publications(tomlfile: Path = TOML):
    return tomllib.loads(tomlfile.read_text(encoding="utf-8")).get("publication", [])


def build_block(pubs):
    return "\n\n".join(render(p) for p in pubs)


def inject(text, block):
    section = f"{START}\n{block}\n        {END}"
    if START in text and END in text:
        return re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            lambda _: section,
            text,
            flags=re.S,
        )
    out, n = re.subn(
        r"(<h2>Publications</h2>\s*)(.*?)(\s*</section>)",
        lambda m: m.group(1) + section + m.group(3),
        text,
        flags=re.S,
    )
    if not n:
        raise SystemExit("Could not find the Publications section in index.html")
    return out


def main():
    pubs = load_publications()
    block = build_block(pubs)
    text = INDEX.read_text(encoding="utf-8")
    new = inject(text, block)

    if "--check" in sys.argv:
        if new != text:
            print("index.html is out of date — run: python tools/build.py")
            sys.exit(1)
        print("index.html is up to date.")
        return

    if new == text:
        print("index.html already up to date.")
    else:
        INDEX.write_text(new, encoding="utf-8")
        print(f"wrote {len(pubs)} publications -> index.html")


if __name__ == "__main__":
    main()
